10-process_and_pid_file

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,5 +1,35 @@
-#!/usr/bin/env bash
-#i love you
-clean_up='rm /var/run/myscript.pid; exit $?'
+#!/bin/bash
 
-echo $$ > "/var/run/myscript.pid"
+# Function to handle signals
+signal_handler() {
+    case $1 in
+        SIGINT)
+            echo "Y U no love me?!" ;;
+        SIGTERM)
+            echo "I hate the kill command" ;;
+        SIGQUIT)
+            cleanup ;;
+    esac
+}
+
+# Function to perform cleanup
+cleanup() {
+    echo "Deleting PID file and terminating"
+    rm -f /var/run/myscript.pid
+    exit 0
+}
+
+# Trap signals and call signal_handler function
+trap 'signal_handler SIGINT' SIGINT
+trap 'signal_handler SIGTERM' SIGTERM
+trap 'signal_handler SIGQUIT' SIGQUIT
+
+# Write PID to file
+echo $$ > /var/run/myscript.pid
+
+# Display message indefinitely
+echo "To infinity and beyond"
+while true; do
+    sleep 1
+    echo "To infinity and beyond"
+done
